language: cpp
compiler: clang++

matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd ./build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make && make test
