dist: trusty
sudo: require

language: cpp
compiler: clang

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - clang-5.0
      - cmake-data
      - cmake
      - g++-6
      

matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
    - pip install --user cpp-coveralls

script:
  - CXX=/usr/bin/clang++-5.0
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd ./build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - ctest -V
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"