language: cpp
compiler: clang

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 -stdlib=libc++"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 -stdlib=libc++"

before_install:
    - eval "${MATRIX_EVAL}"

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd ./build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make && make test
