language: cpp
compiler: clang

install:
- if [ "$CXX" = "clang++" ]; then export CXX="clang++ -std=c++17"; fi

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd ./build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make && make test
